FROM python:3.11-slim

WORKDIR /app

# Copia e instala dependencias Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código
COPY . .

EXPOSE 7001

CMD ["flask", "run", "--host=0.0.0.0", "--port=7001"]

